import type { Config } from "tailwindcss";

// Design tokens ported verbatim from the Stitch export:
// stitch_kenyan_restaurant_management_system/warm_culinary_modernism/DESIGN.md
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "surface-variant": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#59413a",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        outline: "#8d7168",
        "outline-variant": "#e1bfb5",
        "surface-tint": "#ab3504",
        primary: "#a83301",
        "primary-action": "#e05a2b",
        "on-primary": "#ffffff",
        "primary-container": "#ca4a1c",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb59d",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#390b00",
        "on-primary-fixed-variant": "#842500",
        secondary: "#006d30",
        "secondary-action": "#15803d",
        "on-secondary": "#ffffff",
        "secondary-container": "#92f5a4",
        "on-secondary-container": "#007233",
        "secondary-fixed": "#95f8a7",
        "secondary-fixed-dim": "#79db8d",
        "on-secondary-fixed": "#00210a",
        "on-secondary-fixed-variant": "#005323",
        tertiary: "#545c72",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6c748b",
        "on-tertiary-container": "#fefcff",
        "tertiary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#3f465c",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fbf9f5",
        "on-background": "#1b1c1a",
        amber: "#d97706",
        "amber-bg": "#fef3c7",
        "amber-text": "#92400e",
        critical: "#dc2626",
        "critical-bg": "#fee2e2",
        mpesa: "#22c55e",
        "mpesa-bg": "#dcfce7",
        "mpesa-border": "#bbf7d0",
        slate: "#0f172a",
        "slate-border": "#e2e8f0",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-hero-mobile": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "700" }],
        "currency-display": ["1.75rem", { lineHeight: "2rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "currency-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "touch-min": "3rem",
        "touch-comfortable": "3.5rem",
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
      },
      boxShadow: {
        "level-2": "0 4px 12px -2px rgba(224, 90, 43, 0.12)",
        "level-3": "0 -4px 16px -2px rgba(15, 23, 42, 0.08)",
        "level-4": "0 20px 25px -5px rgba(15, 23, 42, 0.15)",
      },
    },
  },
  plugins: [],
};
export default config;
